name: KB to Opensearch

on:
  workflow_dispatch:
  schedule:
    - cron: '*/17 * * * *'

jobs:
  kb-opensearch:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Instalar dependências
        run: pip install -r requirements/kb_opensearch.txt

      - name: Executar script Python
        env:
          API_TOKEN: ${{ secrets.API_TOKEN }}
        run: python kb_opensearch.py
